### ISSUE TITLE
CryoTEMPO- PO.2 - Update MSS from DTU15 to DTU21

### ISSUE THREAD

**Issue by shendric** [shendric/pysiral#75]
Change mean sea surface version in Level-2 processor.

**Comment by djbwork** [comment]
bbb1a92c711af4597ff04b2f8da5139d7da07b05 adds the capability to use MDT22 by adding an options field in auxdata_def.yaml to specify the variable names in the netCDF.

```
    dtu22:
        pyclass: DTUMDTGrid
        long_name: DTU22 mean dynamic topography (1/8 degree grid)
        local_repository: dtu22
        filename: dtu22mdt.nc
        options:
          variables: ['z', null]
        source: null  # Access directly from Stine Kildegaard Rose and Ole Anderson, DTU
```
